services:  
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: news
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

