// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package core

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type News struct {
	ID        int32
	Title     pgtype.Text
	Content   pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
